version: '3.8'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
      - ./dags:/opt/airflow/dags
    working_dir: /app
    command: streamlit run streamlit_app.py  # Replace 'app.py' with your Streamlit app filename

  webserver:
    image: apache/airflow:2.7.1  # Use a valid Airflow image version
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - scheduler

  scheduler:
    image: apache/airflow:2.7.1  # Use a valid Airflow image version
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
